//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTS_MNT.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNT_COST
    {
        public string PREFIX { get; set; }
        public int LOT_NUM { get; set; }
        public System.DateTime WORK_DATE { get; set; }
        public string BADGE_NUMBER { get; set; }
        public short UNIQUE_NUMBER { get; set; }
        public int QUANTITY { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public decimal HOURS_LABOR { get; set; }
        public decimal LABOR_COST { get; set; }
        public decimal MATERIAL_COST { get; set; }
        public decimal MISC_COST { get; set; }
        public decimal WARRANTY_COST { get; set; }
        public decimal CORE_COST { get; set; }
    }
}
