//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTS_MNT.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNT_PAYM
    {
        public string STATION { get; set; }
        public System.DateTime PAY_DATE { get; set; }
        public short VEHICLE_NUMBER { get; set; }
        public int MILEAGE { get; set; }
        public int MILEAGE_PREVIOUS { get; set; }
        public short FUEL { get; set; }
        public int LIFE_MILES { get; set; }
    }
}
