//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTS_MNT.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNT_STWB
    {
        public string LOCATION { get; set; }
        public string SHIFT { get; set; }
        public short BADGE { get; set; }
        public System.DateTime WORK_DATE { get; set; }
        public short VEHICLE { get; set; }
        public short WORK_CODE { get; set; }
        public string COMPLETION_CODE { get; set; }
        public string COMPLETION_CODE_A { get; set; }
        public short WORK_ORDER_NUMBER { get; set; }
        public string WORK_COMPLETED { get; set; }
        public string WORK_CARRYOVER { get; set; }
        public string OTHERS_WORKED { get; set; }
        public short SUPERVISOR_BADGE { get; set; }
        public decimal HOURS_WORKED { get; set; }
        public decimal TOTAL_HOURS { get; set; }
        public short UNITS_COMPLETED { get; set; }
        public string COMMENTS_A { get; set; }
        public string COMMENTS_B { get; set; }
    }
}
