//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTS_MNT.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNT_MHJC
    {
        public short YR { get; set; }
        public short WORK_CODE { get; set; }
        public string COMPLETION_CODE { get; set; }
        public string COMPLETION_CODE_A { get; set; }
        public string BADGE_NUMBER { get; set; }
        public decimal HOURS_1 { get; set; }
        public decimal HOURS_2 { get; set; }
        public decimal HOURS_3 { get; set; }
        public decimal HOURS_4 { get; set; }
        public decimal HOURS_5 { get; set; }
        public decimal HOURS_6 { get; set; }
        public decimal HOURS_7 { get; set; }
        public decimal HOURS_8 { get; set; }
        public decimal HOURS_9 { get; set; }
        public decimal HOURS_10 { get; set; }
        public decimal HOURS_11 { get; set; }
        public decimal HOURS_12 { get; set; }
    }
}
