//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTS_MNT.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNT_BAKE
    {
        public short BUS_NUMBER { get; set; }
        public System.DateTime DATE_BRAKE_OFF { get; set; }
        public string AXLE_POSITION { get; set; }
        public Nullable<System.DateTime> DATE_BRAKE_ON { get; set; }
        public int MILEAGE_BRAKE_ON { get; set; }
        public int MILEAGE_BRAKE_OFF { get; set; }
        public string GARAGE { get; set; }
        public string BAKE_SIZE { get; set; }
        public string BADGE_NUMBER_1 { get; set; }
        public string BADGE_NUMBER_2 { get; set; }
    }
}
