//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTS_MNT.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNT_RCMO
    {
        public string STATION { get; set; }
        public System.DateTime RC_DATE { get; set; }
        public short VEHICLE_NUMBER { get; set; }
        public short WORK_CODE { get; set; }
        public string COMPLETION_CODE { get; set; }
        public string COMPLETION_CODE_A { get; set; }
        public short WORK_ORDER_NUMBER { get; set; }
        public string TROUBLE_REPORTED { get; set; }
        public string CODE_DESCRIPTION { get; set; }
        public string DESCRIPTION { get; set; }
        public string BADGE_NUMBER { get; set; }
        public string REPAIRS_MADE { get; set; }
    }
}
