//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTS_MNT.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNT_WORK
    {
        public short WORK_NUMBER { get; set; }
        public string COMPLETION_CODE { get; set; }
        public string COMPLETION_CODE_A { get; set; }
        public string VEHICLE_IND { get; set; }
        public short OBJECT_CODE { get; set; }
        public string FUNC_CODE { get; set; }
        public string CODE_DESCRIPTION { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal STANDARD_TIME { get; set; }
        public decimal STANDARD_COST { get; set; }
        public short FREQUENCY_HIS { get; set; }
        public decimal HISTORICAL_TIME { get; set; }
        public decimal HISTORICAL_COST { get; set; }
        public string CHARGEABLE_IND { get; set; }
        public string TIME_STUDY { get; set; }
        public string FIVE_YEAR_IND { get; set; }
    }
}
