//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTS_MNT.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNT_VEHICLE
    {
        public short VEHICLE_NUMBER { get; set; }
        public string VEHICLE_TYPE { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
    }
}
