//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTS_MNT.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNT_FDFU
    {
        public System.DateTime FDFU_DATE { get; set; }
        public short VEHICLE { get; set; }
        public short FUEL_HOUR { get; set; }
        public short FUEL_MINUTE { get; set; }
        public short FUEL_SECOND { get; set; }
        public int MILEAGE { get; set; }
        public int PREVIOUS_MILEAGE { get; set; }
        public short FUEL { get; set; }
        public short OIL { get; set; }
        public short COOLANT { get; set; }
        public short TRANS_FLUID { get; set; }
        public string BAD_MILEAGE_IND { get; set; }
        public short BADGE { get; set; }
        public int LIFE_MILES { get; set; }
        public string FUEL_TYPE { get; set; }
        public string CHANGED { get; set; }
    }
}
