//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTS_MNT.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNT_WOEF
    {
        public System.DateTime WOEF_DATE { get; set; }
        public string DIVISION_CODE { get; set; }
        public string BADGE_NUMBER { get; set; }
        public string TEMBS_NUMBER { get; set; }
        public short WORK_CODE { get; set; }
        public string COMPLETION_CODE { get; set; }
        public short VEHICLE_NUMBER { get; set; }
        public short WORK_ORDER_NUMBER { get; set; }
        public short SHIFT { get; set; }
        public short OBJECT_CODE { get; set; }
        public short FUNCTION_CODE { get; set; }
        public decimal HOURS { get; set; }
        public decimal OT_HOURS { get; set; }
        public decimal SPECIAL_RATE { get; set; }
        public string ACLW_IND { get; set; }
        public string COMPLETE_IND { get; set; }
        public string CARRYOVER_IND { get; set; }
        public string SPLIT_IND { get; set; }
        public string BATCH_IND { get; set; }
        public string SUMMARIZED_IND { get; set; }
        public Nullable<System.DateTime> SUMMARIZED_DATE_TIME { get; set; }
        public string DAILY_BATCH_IND { get; set; }
        public Nullable<System.DateTime> DAILY_BATCH_DATE_TIME { get; set; }
        public string REASON_CODE { get; set; }
        public short INSPECTION_NUMBER { get; set; }
        public int MILEAGE { get; set; }
        public Nullable<System.DateTime> ISSUE_DATE { get; set; }
        public string DRIVER_BADGE { get; set; }
        public short UNITS_COMPLETED { get; set; }
        public short START_HOUR { get; set; }
        public short START_MIN { get; set; }
        public short END_HOUR { get; set; }
        public short END_MIN { get; set; }
        public string COMMENTS { get; set; }
        public string LAST_ACTION { get; set; }
        public string CREATED_BY_PROGRAM { get; set; }
        public string CREATED_BY_TEMBS { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string CHANGED_BY_PROGRAM { get; set; }
        public string CHANGED_BY_TEMBS { get; set; }
        public Nullable<System.DateTime> CHANGE_DATE_TIME { get; set; }
    }
}
