//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTS_MNT.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNT_INSP
    {
        public string STATION { get; set; }
        public string INSPECTION_DONE { get; set; }
        public short INSPECTION_TYPE { get; set; }
        public short MILEAGE_VARIANCE { get; set; }
        public short VEHICLE_NUMBER { get; set; }
        public int MILEAGE { get; set; }
        public int MILEAGE_DUE { get; set; }
        public Nullable<System.DateTime> IR_DATE { get; set; }
        public short INSPECTION_NUMBER { get; set; }
        public string PM_INITIALS_1 { get; set; }
        public string PM_IND_1 { get; set; }
        public string PM_INITIALS_2 { get; set; }
        public string PM_IND_2 { get; set; }
        public string PM_INITIALS_3 { get; set; }
        public string PM_IND_3 { get; set; }
        public string PM_INITIALS_4 { get; set; }
        public string PM_IND_4 { get; set; }
        public string PM_INITIALS_5 { get; set; }
        public string PM_IND_5 { get; set; }
        public string PM_INITIALS_6 { get; set; }
        public string PM_IND_6 { get; set; }
        public string PM_INITIALS_7 { get; set; }
        public string PM_IND_7 { get; set; }
        public string PM_INITIALS_8 { get; set; }
        public string PM_IND_8 { get; set; }
        public string PM_INITIALS_9 { get; set; }
        public string PM_IND_9 { get; set; }
        public string PM_INITIALS_10 { get; set; }
        public string PM_IND_10 { get; set; }
        public string PM_INITIALS_11 { get; set; }
        public string PM_IND_11 { get; set; }
        public string PM_INITIALS_12 { get; set; }
        public string PM_IND_12 { get; set; }
        public string PM_INITIALS_13 { get; set; }
        public string PM_IND_13 { get; set; }
        public string PM_INITIALS_14 { get; set; }
        public string PM_IND_14 { get; set; }
        public string PM_INITIALS_15 { get; set; }
        public string PM_IND_15 { get; set; }
        public string PM_INITIALS_16 { get; set; }
        public string PM_IND_16 { get; set; }
        public string PM_CODE_TYPE { get; set; }
        public int LIFE_MILES { get; set; }
        public string CEILING_WASH_IND { get; set; }
    }
}
