//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTS_MNT.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNT_WHPE
    {
        public string COMPLETE_IND { get; set; }
        public string LOCATION { get; set; }
        public short VEHICLE_NUMBER { get; set; }
        public System.DateTime ISSUE_DATE { get; set; }
        public short WORK_CODE { get; set; }
        public string COMPLETION_CODE { get; set; }
        public string COMPLETION_CODE_A { get; set; }
        public short WORK_ORDER_NUMBER { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> COMPLETE_DATE { get; set; }
        public string CAUSE { get; set; }
        public string CODE_DESCRIPTION { get; set; }
        public string DESCRIPTION { get; set; }
        public string COMMENTS_A { get; set; }
        public string COMMENTS_B { get; set; }
        public decimal HOURS { get; set; }
        public decimal COST { get; set; }
        public string MECHANIC_1_BADGE { get; set; }
        public string MECHANIC_2_BADGE { get; set; }
        public string MECHANIC_3_BADGE { get; set; }
        public string ASSIGNED_BY_NUMBER_WH { get; set; }
        public string ASSIGNED_BY_REST_WH { get; set; }
        public string APPROVED_BY_NUMBER_WH { get; set; }
        public string APPROVED_BY_REST_WH { get; set; }
        public short INSPECTION_NUMBER { get; set; }
        public int MILEAGE_DUE_INSP { get; set; }
        public int MILEAGE { get; set; }
    }
}
