//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTS_MNT.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNT_PMSC
    {
        public string CODE_TYPE { get; set; }
        public string PM_INITIALS_1 { get; set; }
        public string PM_DESCRIP_1 { get; set; }
        public int PM_MILE_INC_1 { get; set; }
        public string PM_INITIALS_2 { get; set; }
        public string PM_DESCRIP_2 { get; set; }
        public int PM_MILE_INC_2 { get; set; }
        public string PM_INITIALS_3 { get; set; }
        public string PM_DESCRIP_3 { get; set; }
        public int PM_MILE_INC_3 { get; set; }
        public string PM_INITIALS_4 { get; set; }
        public string PM_DESCRIP_4 { get; set; }
        public int PM_MILE_INC_4 { get; set; }
        public string PM_INITIALS_5 { get; set; }
        public string PM_DESCRIP_5 { get; set; }
        public int PM_MILE_INC_5 { get; set; }
        public string PM_INITIALS_6 { get; set; }
        public string PM_DESCRIP_6 { get; set; }
        public int PM_MILE_INC_6 { get; set; }
        public string PM_INITIALS_7 { get; set; }
        public string PM_DESCRIP_7 { get; set; }
        public int PM_MILE_INC_7 { get; set; }
        public string PM_INITIALS_8 { get; set; }
        public string PM_DESCRIP_8 { get; set; }
        public int PM_MILE_INC_8 { get; set; }
        public string PM_INITIALS_9 { get; set; }
        public string PM_DESCRIP_9 { get; set; }
        public int PM_MILE_INC_9 { get; set; }
        public string PM_INITIALS_10 { get; set; }
        public string PM_DESCRIP_10 { get; set; }
        public int PM_MILE_INC_10 { get; set; }
        public string PM_INITIALS_11 { get; set; }
        public string PM_DESCRIP_11 { get; set; }
        public int PM_MILE_INC_11 { get; set; }
        public string PM_INITIALS_12 { get; set; }
        public string PM_DESCRIP_12 { get; set; }
        public int PM_MILE_INC_12 { get; set; }
        public string PM_INITIALS_13 { get; set; }
        public string PM_DESCRIP_13 { get; set; }
        public int PM_MILE_INC_13 { get; set; }
        public string PM_INITIALS_14 { get; set; }
        public string PM_DESCRIP_14 { get; set; }
        public int PM_MILE_INC_14 { get; set; }
        public string PM_INITIALS_15 { get; set; }
        public string PM_DESCRIP_15 { get; set; }
        public int PM_MILE_INC_15 { get; set; }
        public string PM_INITIALS_16 { get; set; }
        public string PM_DESCRIP_16 { get; set; }
        public int PM_MILE_INC_16 { get; set; }
    }
}
