//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTS_MNT.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNT_BRAK
    {
        public short BUS_NUMBER { get; set; }
        public short LF_TOP { get; set; }
        public short LF_BOT { get; set; }
        public short RF_TOP { get; set; }
        public short RF_BOT { get; set; }
        public short LR_TOP { get; set; }
        public short LR_BOT { get; set; }
        public short RR_TOP { get; set; }
        public short RR_BOT { get; set; }
        public short TL_TOP { get; set; }
        public short TL_BOT { get; set; }
        public short TR_TOP { get; set; }
        public short TR_BOT { get; set; }
        public short PRIORITY_RANK { get; set; }
        public string GARAGE { get; set; }
        public Nullable<System.DateTime> BRAK_DATE { get; set; }
        public int MILEAGE { get; set; }
        public string OS { get; set; }
        public string HIGH_CAM { get; set; }
    }
}
