//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTS_MNT.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNT_REVE
    {
        public short YR { get; set; }
        public short VEHICLE_NUMBER { get; set; }
        public string STATION { get; set; }
        public string FREEWAY_FLYER { get; set; }
        public int PREVIOUS_MILEAGE { get; set; }
        public int PRESENT_MILEAGE { get; set; }
        public int INSP_2500 { get; set; }
        public Nullable<System.DateTime> INSP_CLEAN_DATE { get; set; }
        public int INSP_5000 { get; set; }
        public int INSP_30000 { get; set; }
        public int ANNUAL_MILEAGE { get; set; }
        public int MONTHLY_MILEAGE_1 { get; set; }
        public int MONTHLY_MILEAGE_2 { get; set; }
        public int MONTHLY_MILEAGE_3 { get; set; }
        public int MONTHLY_MILEAGE_4 { get; set; }
        public int MONTHLY_MILEAGE_5 { get; set; }
        public int MONTHLY_MILEAGE_6 { get; set; }
        public int MONTHLY_MILEAGE_7 { get; set; }
        public int MONTHLY_MILEAGE_8 { get; set; }
        public int MONTHLY_MILEAGE_9 { get; set; }
        public int MONTHLY_MILEAGE_10 { get; set; }
        public int MONTHLY_MILEAGE_11 { get; set; }
        public int MONTHLY_MILEAGE_12 { get; set; }
        public short MONTHLY_FUEL_1 { get; set; }
        public short MONTHLY_FUEL_2 { get; set; }
        public short MONTHLY_FUEL_3 { get; set; }
        public short MONTHLY_FUEL_4 { get; set; }
        public short MONTHLY_FUEL_5 { get; set; }
        public short MONTHLY_FUEL_6 { get; set; }
        public short MONTHLY_FUEL_7 { get; set; }
        public short MONTHLY_FUEL_8 { get; set; }
        public short MONTHLY_FUEL_9 { get; set; }
        public short MONTHLY_FUEL_10 { get; set; }
        public short MONTHLY_FUEL_11 { get; set; }
        public short MONTHLY_FUEL_12 { get; set; }
        public short MONTHLY_OIL_1 { get; set; }
        public short MONTHLY_OIL_2 { get; set; }
        public short MONTHLY_OIL_3 { get; set; }
        public short MONTHLY_OIL_4 { get; set; }
        public short MONTHLY_OIL_5 { get; set; }
        public short MONTHLY_OIL_6 { get; set; }
        public short MONTHLY_OIL_7 { get; set; }
        public short MONTHLY_OIL_8 { get; set; }
        public short MONTHLY_OIL_9 { get; set; }
        public short MONTHLY_OIL_10 { get; set; }
        public short MONTHLY_OIL_11 { get; set; }
        public short MONTHLY_OIL_12 { get; set; }
        public short MONTHLY_COOLANT_1 { get; set; }
        public short MONTHLY_COOLANT_2 { get; set; }
        public short MONTHLY_COOLANT_3 { get; set; }
        public short MONTHLY_COOLANT_4 { get; set; }
        public short MONTHLY_COOLANT_5 { get; set; }
        public short MONTHLY_COOLANT_6 { get; set; }
        public short MONTHLY_COOLANT_7 { get; set; }
        public short MONTHLY_COOLANT_8 { get; set; }
        public short MONTHLY_COOLANT_9 { get; set; }
        public short MONTHLY_COOLANT_10 { get; set; }
        public short MONTHLY_COOLANT_11 { get; set; }
        public short MONTHLY_COOLANT_12 { get; set; }
        public short MONTHLY_TRANS_FLUID_1 { get; set; }
        public short MONTHLY_TRANS_FLUID_2 { get; set; }
        public short MONTHLY_TRANS_FLUID_3 { get; set; }
        public short MONTHLY_TRANS_FLUID_4 { get; set; }
        public short MONTHLY_TRANS_FLUID_5 { get; set; }
        public short MONTHLY_TRANS_FLUID_6 { get; set; }
        public short MONTHLY_TRANS_FLUID_7 { get; set; }
        public short MONTHLY_TRANS_FLUID_8 { get; set; }
        public short MONTHLY_TRANS_FLUID_9 { get; set; }
        public short MONTHLY_TRANS_FLUID_10 { get; set; }
        public short MONTHLY_TRANS_FLUID_11 { get; set; }
        public short MONTHLY_TRANS_FLUID_12 { get; set; }
        public string BUS_MAKER { get; set; }
        public short MODEL_YR { get; set; }
        public string LICENSE { get; set; }
        public Nullable<System.DateTime> DATE_DELIVERED { get; set; }
        public int BEGINNING_MILEAGE { get; set; }
        public short SEATS { get; set; }
        public string PUBLIC_ADDRESS { get; set; }
        public string TURBINE { get; set; }
        public short LENGTH_FEET { get; set; }
        public string SPECIAL_BRAKES { get; set; }
        public short INSPECTION_NUMBER { get; set; }
        public string PM_INITIALS_1 { get; set; }
        public int PM_MILE_INC_1 { get; set; }
        public int PM_MILEAGE_1 { get; set; }
        public string PM_INITIALS_2 { get; set; }
        public int PM_MILE_INC_2 { get; set; }
        public int PM_MILEAGE_2 { get; set; }
        public string PM_INITIALS_3 { get; set; }
        public int PM_MILE_INC_3 { get; set; }
        public int PM_MILEAGE_3 { get; set; }
        public string PM_INITIALS_4 { get; set; }
        public int PM_MILE_INC_4 { get; set; }
        public int PM_MILEAGE_4 { get; set; }
        public string PM_INITIALS_5 { get; set; }
        public int PM_MILE_INC_5 { get; set; }
        public int PM_MILEAGE_5 { get; set; }
        public string PM_INITIALS_6 { get; set; }
        public int PM_MILE_INC_6 { get; set; }
        public int PM_MILEAGE_6 { get; set; }
        public string PM_INITIALS_7 { get; set; }
        public int PM_MILE_INC_7 { get; set; }
        public int PM_MILEAGE_7 { get; set; }
        public string PM_INITIALS_8 { get; set; }
        public int PM_MILE_INC_8 { get; set; }
        public int PM_MILEAGE_8 { get; set; }
        public string PM_INITIALS_9 { get; set; }
        public int PM_MILE_INC_9 { get; set; }
        public int PM_MILEAGE_9 { get; set; }
        public string PM_INITIALS_10 { get; set; }
        public int PM_MILE_INC_10 { get; set; }
        public int PM_MILEAGE_10 { get; set; }
        public string PM_INITIALS_11 { get; set; }
        public int PM_MILE_INC_11 { get; set; }
        public int PM_MILEAGE_11 { get; set; }
        public string PM_INITIALS_12 { get; set; }
        public int PM_MILE_INC_12 { get; set; }
        public int PM_MILEAGE_12 { get; set; }
        public string PM_INITIALS_13 { get; set; }
        public int PM_MILE_INC_13 { get; set; }
        public int PM_MILEAGE_13 { get; set; }
        public string PM_INITIALS_14 { get; set; }
        public int PM_MILE_INC_14 { get; set; }
        public int PM_MILEAGE_14 { get; set; }
        public string PM_INITIALS_15 { get; set; }
        public int PM_MILE_INC_15 { get; set; }
        public int PM_MILEAGE_15 { get; set; }
        public string PM_INITIALS_16 { get; set; }
        public int PM_MILE_INC_16 { get; set; }
        public int PM_MILEAGE_16 { get; set; }
        public string PM_CODE_TYPE { get; set; }
        public Nullable<System.DateTime> HUBO_DATE { get; set; }
        public short CEILING_WASH_COUNT { get; set; }
        public short CARD_NUMBER { get; set; }
        public string PREVIOUS_STATION { get; set; }
        public Nullable<System.DateTime> DATE_BUS_OOS { get; set; }
        public string AVL_IND { get; set; }
        public string APC_IND { get; set; }
        public string ANN_IND { get; set; }
        public string FLAG1_IND { get; set; }
        public string FLAG2_IND { get; set; }
        public string FLAG3_IND { get; set; }
        public string VIN_NUM { get; set; }
        public Nullable<System.DateTime> DATE_XFER_TO_GARAGE { get; set; }
        public Nullable<int> LIFE_MILES_AT_XFER { get; set; }
        public Nullable<System.DateTime> DATE_BUS_ACCEPTED { get; set; }
    }
}
