//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTS_MNT.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNT_TANK
    {
        public System.DateTime DT_DATE { get; set; }
        public string STATION { get; set; }
        public short BADGE { get; set; }
        public short TIME { get; set; }
        public short BUS_NUMBER { get; set; }
        public int MILEAGE { get; set; }
        public short FUEL { get; set; }
        public short OIL { get; set; }
        public short COOLANT { get; set; }
        public int LIFE_MILES { get; set; }
    }
}
