//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTS_MNT.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNT_RCAH
    {
        public short YR { get; set; }
        public short WORK_CODE { get; set; }
        public string COMPLETION_CODE { get; set; }
        public string COMPLETION_CODE_A { get; set; }
        public string STATION { get; set; }
        public string CODE_DESCRIPTION { get; set; }
        public string DESCRIPTION { get; set; }
        public short MO_ACCUM_1 { get; set; }
        public short MO_ACCUM_2 { get; set; }
        public short MO_ACCUM_3 { get; set; }
        public short MO_ACCUM_4 { get; set; }
        public short MO_ACCUM_5 { get; set; }
        public short MO_ACCUM_6 { get; set; }
        public short MO_ACCUM_7 { get; set; }
        public short MO_ACCUM_8 { get; set; }
        public short MO_ACCUM_9 { get; set; }
        public short MO_ACCUM_10 { get; set; }
        public short MO_ACCUM_11 { get; set; }
        public short MO_ACCUM_12 { get; set; }
    }
}
