//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTS_MNT.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNT_TOOL
    {
        public string LAST_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_INIT_EXT { get; set; }
        public short UNIQUE_NUMBER { get; set; }
        public string TEMBS_NUMBER { get; set; }
        public string DESCRIPTION_50 { get; set; }
        public Nullable<System.DateTime> DATE_GIVEN { get; set; }
    }
}
