//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTS_MNT.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNT_CARD
    {
        public short YR { get; set; }
        public string STATION { get; set; }
        public string COMPLETE { get; set; }
        public short VEHICLE_NUMBER_CARD { get; set; }
        public short CARD_NUMBER { get; set; }
        public int INSP_DUE_MILEAGE { get; set; }
        public int INSP_MILEAGE { get; set; }
        public int WORK_MILEAGE_CARD { get; set; }
        public Nullable<System.DateTime> INSP_DATE { get; set; }
        public int MILES_TRAVELLED_INSP { get; set; }
        public int MILES_TRAVELLED_WORK { get; set; }
        public int HUBO_MILEAGE { get; set; }
    }
}
