//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTS_MNT.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNT_INSC
    {
        public int UNIQUE_NBR { get; set; }
        public string TYPE_CODE { get; set; }
        public short ORDER_NBR { get; set; }
        public string INSPECTION_DESC { get; set; }
        public short COLUMN_LIST { get; set; }
        public string OK_DEFECT_LINE { get; set; }
    }
}
