//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTS_MNT.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNT_PUIN
    {
        public string STATION { get; set; }
        public System.DateTime PUIN_DATE { get; set; }
        public short AM_PULLOUTS { get; set; }
        public short CALL_BUSES { get; set; }
        public short AM_SERVICE { get; set; }
        public short AM_TROLLEY_SERVICE { get; set; }
        public short TROLLEYS_IN_WORK { get; set; }
        public short BUSES_IN_SHOP { get; set; }
        public short TROLLEYS_IN_SHOP { get; set; }
        public short A_BUSES_IN_WORK { get; set; }
        public short A_BUSES_FLEET_MAINT { get; set; }
        public short A_BUSES_PARTS { get; set; }
        public short INSPECTION_BUSES { get; set; }
        public short WASH_BUSES { get; set; }
        public short CHARTERS { get; set; }
        public short OK_TROLLEYS { get; set; }
        public short OK_BUSES { get; set; }
        public short WORK_BUSES { get; set; }
        public short STORAGE_BUSES { get; set; }
        public short SPECIAL { get; set; }
        public short LOANERS { get; set; }
        public short RADIO { get; set; }
        public short PM_PULLOUTS { get; set; }
    }
}
