//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTS_MNT.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNT_MIMA
    {
        public short VEHICLE_TYPE { get; set; }
        public int MIN_MILES_TRAVELED { get; set; }
        public int MAX_MILES_TRAVELED_M { get; set; }
        public decimal MIN_MPG { get; set; }
        public decimal MAX_MPG { get; set; }
        public short MIN_GALS_DIESEL { get; set; }
        public short MAX_GALS_DIESEL { get; set; }
        public short MIN_GALS_UNLEADED { get; set; }
        public short MAX_GALS_UNLEADED { get; set; }
        public short MIN_QTS_OIL { get; set; }
        public short MAX_QTS_OIL { get; set; }
        public int STAN_MILES_TRAVELED { get; set; }
    }
}
