//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTS_MNT.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNT_AUTO
    {
        public short FUEL_YR { get; set; }
        public short AUTO_NUMBER { get; set; }
        public string IDENTIFICATION { get; set; }
        public string MAKE { get; set; }
        public short MODEL_YR { get; set; }
        public string LICENSE { get; set; }
        public string USE { get; set; }
        public string LOCATION { get; set; }
        public short MONTHLY_FUEL_1 { get; set; }
        public short MONTHLY_FUEL_2 { get; set; }
        public short MONTHLY_FUEL_3 { get; set; }
        public short MONTHLY_FUEL_4 { get; set; }
        public short MONTHLY_FUEL_5 { get; set; }
        public short MONTHLY_FUEL_6 { get; set; }
        public short MONTHLY_FUEL_7 { get; set; }
        public short MONTHLY_FUEL_8 { get; set; }
        public short MONTHLY_FUEL_9 { get; set; }
        public short MONTHLY_FUEL_10 { get; set; }
        public short MONTHLY_FUEL_11 { get; set; }
        public short MONTHLY_FUEL_12 { get; set; }
        public short MONTHLY_OIL_1 { get; set; }
        public short MONTHLY_OIL_2 { get; set; }
        public short MONTHLY_OIL_3 { get; set; }
        public short MONTHLY_OIL_4 { get; set; }
        public short MONTHLY_OIL_5 { get; set; }
        public short MONTHLY_OIL_6 { get; set; }
        public short MONTHLY_OIL_7 { get; set; }
        public short MONTHLY_OIL_8 { get; set; }
        public short MONTHLY_OIL_9 { get; set; }
        public short MONTHLY_OIL_10 { get; set; }
        public short MONTHLY_OIL_11 { get; set; }
        public short MONTHLY_OIL_12 { get; set; }
        public short MONTHLY_COOLANT_1 { get; set; }
        public short MONTHLY_COOLANT_2 { get; set; }
        public short MONTHLY_COOLANT_3 { get; set; }
        public short MONTHLY_COOLANT_4 { get; set; }
        public short MONTHLY_COOLANT_5 { get; set; }
        public short MONTHLY_COOLANT_6 { get; set; }
        public short MONTHLY_COOLANT_7 { get; set; }
        public short MONTHLY_COOLANT_8 { get; set; }
        public short MONTHLY_COOLANT_9 { get; set; }
        public short MONTHLY_COOLANT_10 { get; set; }
        public short MONTHLY_COOLANT_11 { get; set; }
        public short MONTHLY_COOLANT_12 { get; set; }
        public short MONTHLY_TRANS_FLUID_1 { get; set; }
        public short MONTHLY_TRANS_FLUID_2 { get; set; }
        public short MONTHLY_TRANS_FLUID_3 { get; set; }
        public short MONTHLY_TRANS_FLUID_4 { get; set; }
        public short MONTHLY_TRANS_FLUID_5 { get; set; }
        public short MONTHLY_TRANS_FLUID_6 { get; set; }
        public short MONTHLY_TRANS_FLUID_7 { get; set; }
        public short MONTHLY_TRANS_FLUID_8 { get; set; }
        public short MONTHLY_TRANS_FLUID_9 { get; set; }
        public short MONTHLY_TRANS_FLUID_10 { get; set; }
        public short MONTHLY_TRANS_FLUID_11 { get; set; }
        public short MONTHLY_TRANS_FLUID_12 { get; set; }
        public int MONTHLY_MILEAGE_1 { get; set; }
        public int MONTHLY_MILEAGE_2 { get; set; }
        public int MONTHLY_MILEAGE_3 { get; set; }
        public int MONTHLY_MILEAGE_4 { get; set; }
        public int MONTHLY_MILEAGE_5 { get; set; }
        public int MONTHLY_MILEAGE_6 { get; set; }
        public int MONTHLY_MILEAGE_7 { get; set; }
        public int MONTHLY_MILEAGE_8 { get; set; }
        public int MONTHLY_MILEAGE_9 { get; set; }
        public int MONTHLY_MILEAGE_10 { get; set; }
        public int MONTHLY_MILEAGE_11 { get; set; }
        public int MONTHLY_MILEAGE_12 { get; set; }
        public int CURRENT_MILEAGE { get; set; }
        public int YEAR_END_MILEAGE { get; set; }
        public int INSPECTION_MILEAGE { get; set; }
        public Nullable<System.DateTime> INSPECTION_DATE { get; set; }
        public short INSPECTION_MILEAGE_VAR { get; set; }
        public short INSPECTION_DATE_VAR { get; set; }
        public string SUPERVISORY { get; set; }
        public string FUEL_IT { get; set; }
        public string AVL_IND { get; set; }
        public string APC_IND { get; set; }
        public string ANN_IND { get; set; }
        public string FLAG1_IND { get; set; }
        public string FLAG2_IND { get; set; }
        public string FLAG3_IND { get; set; }
        public short ASSET_ID { get; set; }
    }
}
