//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTS_MNT.EntityDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EntitiesMNT : DbContext
    {
        public EntitiesMNT()
            : base("name=EntitiesMNT")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MNT_AUTO> MNT_AUTO { get; set; }
        public virtual DbSet<MNT_BAKE> MNT_BAKE { get; set; }
        public virtual DbSet<MNT_BDIN> MNT_BDIN { get; set; }
        public virtual DbSet<MNT_BRAK> MNT_BRAK { get; set; }
        public virtual DbSet<MNT_CARD> MNT_CARD { get; set; }
        public virtual DbSet<MNT_COST> MNT_COST { get; set; }
        public virtual DbSet<MNT_CTRL> MNT_CTRL { get; set; }
        public virtual DbSet<MNT_FDFU> MNT_FDFU { get; set; }
        public virtual DbSet<MNT_FLET> MNT_FLET { get; set; }
        public virtual DbSet<MNT_INSC> MNT_INSC { get; set; }
        public virtual DbSet<MNT_KKFU> MNT_KKFU { get; set; }
        public virtual DbSet<MNT_MHJC> MNT_MHJC { get; set; }
        public virtual DbSet<MNT_MIMA> MNT_MIMA { get; set; }
        public virtual DbSet<MNT_PAYM> MNT_PAYM { get; set; }
        public virtual DbSet<MNT_PMSC> MNT_PMSC { get; set; }
        public virtual DbSet<MNT_PUIN> MNT_PUIN { get; set; }
        public virtual DbSet<MNT_RCAH> MNT_RCAH { get; set; }
        public virtual DbSet<MNT_STND> MNT_STND { get; set; }
        public virtual DbSet<MNT_TANK> MNT_TANK { get; set; }
        public virtual DbSet<MNT_TBAD> MNT_TBAD { get; set; }
        public virtual DbSet<MNT_TOOL> MNT_TOOL { get; set; }
        public virtual DbSet<MNT_VEHICLE> MNT_VEHICLE { get; set; }
        public virtual DbSet<MNT_WORK> MNT_WORK { get; set; }
        public virtual DbSet<MNT_WHPE> MNT_WHPE { get; set; }
        public virtual DbSet<MNT_INSP> MNT_INSP { get; set; }
        public virtual DbSet<MNT_WOEF> MNT_WOEF { get; set; }
        public virtual DbSet<MNT_STWB> MNT_STWB { get; set; }
        public virtual DbSet<MNT_REVE> MNT_REVE { get; set; }
        public virtual DbSet<MNT_RCMO> MNT_RCMO { get; set; }
        public virtual DbSet<MNT_RTRQ> MNT_RTRQ { get; set; }
    
        public virtual int MNFUEL8000_BATCH_UPDATE_FUEL(string p_STATION, ObjectParameter p_FUEL_RECORDS_READ, ObjectParameter p_REVE_RECS_UPDATED, ObjectParameter p_REVE_ERRORS, ObjectParameter p_INSP_RECS_CREATED, ObjectParameter p_INSP_ERRORS, ObjectParameter p_TANK_RECS_CREATED, ObjectParameter p_TANK_ERRORS, ObjectParameter p_PAYM_RECS_CREATED, ObjectParameter p_PAYM_ERRORS, ObjectParameter p_FUEL_DATE, ObjectParameter p_ERRORS, ObjectParameter p_ERRCODE, ObjectParameter p_ERRMSG, ObjectParameter p_COMMENTS)
        {
            var p_STATIONParameter = p_STATION != null ?
                new ObjectParameter("P_STATION", p_STATION) :
                new ObjectParameter("P_STATION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MNFUEL8000_BATCH_UPDATE_FUEL", p_STATIONParameter, p_FUEL_RECORDS_READ, p_REVE_RECS_UPDATED, p_REVE_ERRORS, p_INSP_RECS_CREATED, p_INSP_ERRORS, p_TANK_RECS_CREATED, p_TANK_ERRORS, p_PAYM_RECS_CREATED, p_PAYM_ERRORS, p_FUEL_DATE, p_ERRORS, p_ERRCODE, p_ERRMSG, p_COMMENTS);
        }
    }
}
